### ISSUE TITLE
[JOSS review] typos in the paper

### ISSUE THREAD

**Issue by tmigot** [UncertainLab/Enlsip.jl#3]
- [x] Typos:
   - [x] At least once ENLSIP was noted ENLISP.
   - [x] "It implements a nonlinear least squares under nonlinear constraints solver" -> "It implements a solver for nonlinear least squares with nonlinear constraints"

- [x] * Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?* I think the theoretical guarantees offer by the solver should be clarified for a general audience. For instance, I assume this is not a global optimizer. In general, the paper should target a broad audience.
- [x] I think the paper lacks a brief description of the algorithm. It is not clear if this uses the second-order derivatives of the involved function or if the active-set strategy used in the paper is exactly the same as in the book by Nocedal & Wright ...
- [x] *Data sharing: If the paper contains original data, data are accessible to the reviewers. If the paper contains no original data, please check this item.* A large part of the discussion in the paper is comparing the Fortran version vs. the Julia version while there is no shared data on this.
- [x] This recent post could help the author expand the list of existing solvers for (unconstrained) NLS **https://discourse.julialang.org/t/comparing-non-linear-least-squares-solvers/104752**.
- [x] It would also help states why we consider the NLS case separately to the classical optimization case.

https://github.com/openjournals/joss-reviews/issues/6226

**Comment by pierre-borie** [comment]
Thank you for your feedback and sorry for taking this much time to respond. 
I agree on your suggestion to clarify the theoritical guarantees but shouldn't I redirect to the [documentation](https://uncertainlab.github.io/Enlsip.jl/dev/) for a description of the method? I might be wrong about it but I wanted to keep the optimization aspects of the paper brief and just state in what category the method belongs to.
Also thanks for the topic comparing least squares solvers packages!

**Comment by tmigot** [comment]
It is true, though but it is possible to give a short description of the algorithm in 2-3 sentences.

**Comment by pierre-borie** [comment]
Hi! I just pushed a revised version of the paper of the joss-paper branch. I added a brief description of the algorithm and the theoretical guarantees in addition to a paragraph on comparison tests between Julia and Fortran.

**Comment by jbytecode** [comment]
Can we close this issue when it is done?

**Comment by tmigot** [comment]
Hi @pierre-borie ! I have more comments regarding the paper:

- [x] Typos:
- least squares OR least-squares
- missing "problem" in first sentence (and elsewhere)
- "This type of problems" plural/singular
In general, please, revise carefully the English.
- [x] Mention somewhere that the aim is to find a local minimum of the problem. I noticed it is well done in the documentation of the package.
- [x] Is Figure 1 a Dolan&Moré performance profile? Why the percentage is 100% with 26 problems failed?
- [x] The package JSOSolvers.jl has least squares variants for the solvers TRUNK (unconstrained) and TRON (bound-constrained).
- [x] I would use citation for the different packages when available instead of just naming them. You can usually find citation file or use Github "Cite this repository" on packages' Github page.

**Comment by pierre-borie** [comment]
Hi @tmigot , thanks for your comments! Just to make sure I get these right:

- I deliberatly distinguished "least squares" from "least-squares". I use the latter as an adjective, kind of, like in "least-squares problem" or "least-squares structure" but I'll uniformize it to avoid any ambiguities;
- Figure 1 is indeed a "home made" Dolan-Moré performance profile; the percentage was still 100% because both versions failed on the same problems and we then excluded them from the test set, which is not very clear in the paper I agree. I'll replace the performance profile by a graph obtained with the BenchmarkProfiles.jl package and will correct the percentage issue at the same time.

**Comment by pierre-borie** [comment]
@tmigot - I submitted a new version of the paper that will, I hope, address your latest comments!
