### ISSUE TITLE
Reproducible example with Ipopt in tutorial

### ISSUE THREAD

**Issue by tmigot** [UncertainLab/Enlsip.jl#6]
In the tutorial, there is a table with numerical resutls from Ipopt.
This comparison is difficult to assess because there is no reproducible code for this example.

I would suggest to either add the code or simply remove the table. It is not clear from this table how comparable the two solves are, for instance, do they have the same stopping criteria?

https://github.com/openjournals/joss-reviews/issues/6226

**Comment by pierre-borie** [comment]
I think it's relevant; the idea is just to show what can be expected in terms of computation times. I added the modeling code of the problem with JuMP (and its solving with ipopt). I hope it will clarify the comparison.

#10
