### ISSUE TITLE
Add tolerance as input argument

### ISSUE THREAD

**Issue by tmigot** [UncertainLab/Enlsip.jl#8]
I imagine a potential user would most likely be interested in setting the stopping tolerance by himself.
Besides, I don't think the stopping criterion is explicited somewhere in the documentation

https://github.com/openjournals/joss-reviews/issues/6226

**Comment by pierre-borie** [comment]
Indeed, a description of the stopping criteria was clearly missing. I added one to the documentation. Tolerances can be passed as keyword arguments of the main solving function. 

#10
